name = "processor_task-flow"
compatibility_date = "2024-09-11"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTA2OTQ2NjQtOGRhOC00ZTdkLTg3NGQtNmRlYmYzMGVjMjc3IiwidGVuYW50X2lkIjoiN2RhNDZkZTYwYmUyNGNlN2E5ODg2MDNjN2FjZjU2MTc3NTkxMzc5ZDAwZmE0MWE0MTBjMjg5NDQyODdjOGU2NyIsImludGVybmFsX3NlY3JldCI6Ijg1OGQ0NzhhLWJjYWUtNDMxNi1iM2VmLWNmODliMWMzOWU2MCJ9.weOcttDGQK-ozj8rLiV0upghTVuwNNT9-GPX1GCohdY"

# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"